In [1]:
import numpy as np

def create_array():
    print("Select the type of array to create:")
    print("1. 1D Array")
    print("2. 2D Array")
    print("3. 3D Array")
    choice = int(input("Enter your choice: "))
    if choice == 1:
        elements = list(map(int, input("Enter elements separated by space: ").split()))
        arr = np.array(elements)
    elif choice == 2:
        rows = int(input("Enter number of rows: "))
        cols = int(input("Enter number of columns: "))
        elements = list(map(int, input(f"Enter {rows * cols} elements separated by space: ").split()))
        arr = np.array(elements).reshape(rows, cols)
    elif choice == 3:
        depth = int(input("Enter depth: "))
        rows = int(input("Enter number of rows: "))
        cols = int(input("Enter number of columns: "))
        elements = list(map(int, input(f"Enter {depth * rows * cols} elements separated by space: ").split()))
        arr = np.array(elements).reshape(depth, rows, cols)
    else:
        print("Invalid choice!")
        return None
    print("Array created successfully:")
    print(arr)
    return arr

def mathematical_operations(arr):
    print("Choose a mathematical operation:")
    print("1. Addition")
    print("2. Subtraction")
    print("3. Multiplication")
    print("4. Division")
    choice = int(input("Enter your choice: "))
    elements = list(map(int, input(f"Enter {arr.size} elements for second array: ").split()))
    arr2 = np.array(elements).reshape(arr.shape)
    if choice == 1:
        result = arr + arr2
        print("Result of Addition:")
    elif choice == 2:
        result = arr - arr2
        print("Result of Subtraction:")
    elif choice == 3:
        result = arr * arr2
        print("Result of Multiplication:")
    elif choice == 4:
        result = arr / arr2
        print("Result of Division:")
    else:
        print("Invalid choice!")
        return
    print(result)

def combine_or_split(arr):
    print("Choose an option:")
    print("1. Combine Arrays")
    print("2. Split Array")
    choice = int(input("Enter your choice: "))
    if choice == 1:
        elements = list(map(int, input(f"Enter {arr.size} elements for another array: ").split()))
        arr2 = np.array(elements).reshape(arr.shape)
        combined = np.vstack((arr, arr2))
        print("Combined Array:")
        print(combined)
    elif choice == 2:
        print("Splitting array into 2 equal parts...")
        split_arrays = np.array_split(arr, 2)
        for i, part in enumerate(split_arrays):
            print(f"Part {i+1}:")
            print(part)
    else:
        print("Invalid choice!")

def indexing_and_slicing(arr):
    while True:
        print("Choose an operation:")
        print("1. Indexing")
        print("2. Slicing")
        print("3. Go Back")
        choice = int(input("Enter your choice: "))
        if choice == 1:
            if arr.ndim == 1:
                idx = int(input("Enter index: "))
                print("Value:", arr[idx])
            elif arr.ndim == 2:
                r = int(input("Enter row index: "))
                c = int(input("Enter column index: "))
                print("Value:", arr[r][c])
            elif arr.ndim == 3:
                d = int(input("Enter depth index: "))
                r = int(input("Enter row index: "))
                c = int(input("Enter column index: "))
                print("Value:", arr[d][r][c])
        elif choice == 2:
            print("Enter slicing in Python format, e.g. 0:2 or :3")
            if arr.ndim == 1:
                s = input("Enter slice: ")
                print("Result:", arr[eval(f"slice({s.replace(':', ',')})")])
            elif arr.ndim == 2:
                r = input("Enter row slice: ")
                c = input("Enter column slice: ")
                print("Sliced Array:")
                print(arr[eval(f"slice({r.replace(':', ',')})"), eval(f"slice({c.replace(':', ',')})")])
            elif arr.ndim == 3:
                d = input("Enter depth slice: ")
                r = input("Enter row slice: ")
                c = input("Enter column slice: ")
                print("Sliced Array:")
                print(arr[eval(f"slice({d.replace(':', ',')})"), eval(f"slice({r.replace(':', ',')})"), eval(f"slice({c.replace(':', ',')})")])
        elif choice == 3:
            print("Going back to main menu...")
            break
        else:
            print("Invalid choice!")

def search_sort_filter(arr):
    print("Choose an option:")
    print("1. Search value")
    print("2. Sort array")
    print("3. Filter values")
    choice = int(input("Enter your choice: "))
    if choice == 1:
        val = int(input("Enter value to search: "))
        result = np.where(arr == val)
        print(f"Value found at: {result}")
    elif choice == 2:
        sorted_arr = np.sort(arr)
        print("Sorted Array:")
        print(sorted_arr)
    elif choice == 3:
        val = int(input("Enter threshold value: "))
        filtered = arr[arr > val]
        print("Filtered Values greater than", val, ":")
        print(filtered)
    else:
        print("Invalid choice!")

def aggregate_statistics(arr):
    print("Choose an operation:")
    print("1. Sum")
    print("2. Mean")
    print("3. Median")
    print("4. Standard Deviation")
    choice = int(input("Enter your choice: "))
    if choice == 1:
        print("Sum =", np.sum(arr))
    elif choice == 2:
        print("Mean =", np.mean(arr))
    elif choice == 3:
        print("Median =", np.median(arr))
    elif choice == 4:
        print("Standard Deviation =", np.std(arr))
    else:
        print("Invalid choice!")

def main():
    arr = None
    while True:
        print("===== NumPy Analyzer =====")
        print("1. Create Array")
        print("2. Mathematical Operations")
        print("3. Combine or Split Arrays")
        print("4. Indexing and Slicing")
        print("5. Search, Sort, or Filter")
        print("6. Aggregates and Statistics")
        print("7. Exit")
        choice = int(input("Enter your choice: "))
        if choice == 1:
            arr = create_array()
        elif choice == 2 and arr is not None:
            mathematical_operations(arr)
        elif choice == 3 and arr is not None:
            combine_or_split(arr)
        elif choice == 4 and arr is not None:
            indexing_and_slicing(arr)
        elif choice == 5 and arr is not None:
            search_sort_filter(arr)
        elif choice == 6 and arr is not None:
            aggregate_statistics(arr)
        elif choice == 7:
            print("Exiting program. Thank you!")
            break
        else:
            print("Please create an array first!")

if __name__ == "__main__":
    main()


===== NumPy Analyzer =====
1. Create Array
2. Mathematical Operations
3. Combine or Split Arrays
4. Indexing and Slicing
5. Search, Sort, or Filter
6. Aggregates and Statistics
7. Exit


Enter your choice:  1


Select the type of array to create:
1. 1D Array
2. 2D Array
3. 3D Array


Enter your choice:  2
Enter number of rows:  2
Enter number of columns:  3
Enter 6 elements separated by space:  10 20 30 40 50 60


Array created successfully:
[[10 20 30]
 [40 50 60]]
===== NumPy Analyzer =====
1. Create Array
2. Mathematical Operations
3. Combine or Split Arrays
4. Indexing and Slicing
5. Search, Sort, or Filter
6. Aggregates and Statistics
7. Exit


Enter your choice:  2


Choose a mathematical operation:
1. Addition
2. Subtraction
3. Multiplication
4. Division


Enter your choice:  2
Enter 6 elements for second array:  5 5 5 5 5 5


Result of Subtraction:
[[ 5 15 25]
 [35 45 55]]
===== NumPy Analyzer =====
1. Create Array
2. Mathematical Operations
3. Combine or Split Arrays
4. Indexing and Slicing
5. Search, Sort, or Filter
6. Aggregates and Statistics
7. Exit


Enter your choice:  2 


Choose a mathematical operation:
1. Addition
2. Subtraction
3. Multiplication
4. Division


Enter your choice:  1
Enter 6 elements for second array:   1 2 3 4 4 6


Result of Addition:
[[11 22 33]
 [44 54 66]]
===== NumPy Analyzer =====
1. Create Array
2. Mathematical Operations
3. Combine or Split Arrays
4. Indexing and Slicing
5. Search, Sort, or Filter
6. Aggregates and Statistics
7. Exit


Enter your choice:  3


Choose an option:
1. Combine Arrays
2. Split Array


Enter your choice:  2


Splitting array into 2 equal parts...
Part 1:
[[10 20 30]]
Part 2:
[[40 50 60]]
===== NumPy Analyzer =====
1. Create Array
2. Mathematical Operations
3. Combine or Split Arrays
4. Indexing and Slicing
5. Search, Sort, or Filter
6. Aggregates and Statistics
7. Exit


Enter your choice:   1


Select the type of array to create:
1. 1D Array
2. 2D Array
3. 3D Array


Enter your choice:  6


Invalid choice!
===== NumPy Analyzer =====
1. Create Array
2. Mathematical Operations
3. Combine or Split Arrays
4. Indexing and Slicing
5. Search, Sort, or Filter
6. Aggregates and Statistics
7. Exit


Enter your choice:  7


Exiting program. Thank you!
